namespace OnlyWar.Models.Planets
{
    public static class TempPlanetList
    {
        public static string[] PlanetNames = new string[]
        {
            "42 Hydra Tertius",
            "Abandoned Hope",
            "Abheilüng",
            "Absolom Reach",
            "Accatran",
            "Acheron IV",
            "Acralem",
            "Acreage",
            "Adacore",
            "Adrantis Five",
            "Adumbria",
            "Aerius",
            "Aggaros",
            "Aghoru",
            "Agripinaa",
            "Aktosha",
            "Al-Arach",
            "Alantor X",
            "Alayran",
            "Albert IV",
            "Albitern",
            "Alfrost",
            "Algol",
            "Algol Nine",
            "Almarit",
            "Alpha Shalish",
            "Altaneum",
            "Altarak",
            "Altid 156",
            "Amarah Prime",
            "Ambold Eleven",
            "Amerigo Secundus",
            "Amistel",
            "Amistel Majoris",
            "Amun'an Morrus",
            "Anark Zeta",
            "Anathrax",
            "Andronicus Prime",
            "Anemae Gulfward",
            "Anshur",
            "Antax",
            "Antecanis IV",
            "Antioc",
            "Anvilus Nine",
            "Anzyra",
            "Aquilon",
            "Arach-Cyn",
            "Aralan",
            "Arcadia",
            "Arcadia (Eldar)",
            "Arcetri",
            "Archaos",
            "Archipelaga",
            "Arconar",
            "Argentor",
            "Arimaspia",
            "Ariyo",
            "Ark Reach Secundus",
            "Arkhona",
            "Arkunasha",
            "Armageddon",
            "Armato",
            "Arminiun",
            "Artemia Majoris",
            "Arthas",
            "Arthas Moloch",
            "Arthos",
            "Arx",
            "Aryand",
            "Asgard",
            "Ashek II",
            "Asherkin",
            "Askelphion Secundus",
            "Asur",
            "Atalia Minoris",
            "Atari Vo",
            "Athonos",
            "Attila",
            "Au'taal",
            "Augura",
            "Aumet",
            "Aurelia",
            "Auric",
            "Autega",
            "Avellorn",
            "Avignor",
            "Avitohol",
            "Azbaragus",
            "Azoras",
            "Baal",
            "Baal Secundus",
            "Baalus Trine",
            "Badab Primaris",
            "Bakka",
            "Bakus III",
            "Balhaut",
            "Balle Prime",
            "Balthasar",
            "Balur",
            "Balzac",
            "Banish",
            "Banna",
            "Baran",
            "Baraspine",
            "Barbarus",
            "Barbarus Prime",
            "Baroda",
            "Bastonbeil",
            "Behtle V",
            "Bekrin",
            "Belacane",
            "Belaeno",
            "Belahaam",
            "Belatis IV",
            "Belial",
            "Belial IV",
            "Belis Corona",
            "Bellicas",
            "Belphago",
            "Berien VI",
            "Berin",
            "Beshic V",
            "Beta Fortanis",
            "Beta-Garmon II",
            "Beta-Garmon III",
            "Betalis III",
            "Betalis IV",
            "Biegel 9",
            "Bifrost",
            "Birmingham",
            "Black Reach",
            "Blackwater",
            "Bleakfrost",
            "Blitzen",
            "Bloodfall",
            "Boonhaven",
            "Bora Culpa",
            "Bork'an",
            "Boros",
            "Boros Prime",
            "Bray",
            "Bren's World",
            "Brendine II",
            "Brezal III",
            "Brigannion Four",
            "Brimlock",
            "Britan",
            "Bront",
            "Brun",
            "Brycantia",
            "Bubonicus",
            "Bulwark",
            "Burjan's World",
            "Byssta",
            "Cadia",
            "Caer Malafori",
            "Calderis",
            "Caliban",
            "Calth",
            "Camgia",
            "Canak",
            "Candau",
            "Cano'var",
            "Canopus",
            "Carandinis VII",
            "Carcharias",
            "Cardrim",
            "Carlos McConnell",
            "Carnac",
            "Carpathia",
            "Carrion Deep",
            "Caruana-W",
            "Cassell",
            "Castix VIII",
            "Catachan",
            "Ceocan",
            "Cesstium",
            "Chaemos",
            "Chandrax II",
            "Chaoku-Minor",
            "Charadon",
            "Chaspia",
            "Chemos",
            "Chiros",
            "Chordelis",
            "Chosin",
            "Cinchare",
            "Cinderus XI",
            "Circe",
            "Clax",
            "Cloister",
            "Clove",
            "Cocholos",
            "Cociaminus",
            "Colcha",
            "Colchis",
            "Conovar",
            "Constantinium",
            "Coralax",
            "Corinal",
            "Coronis Agathon",
            "Coseflame",
            "Cousteau XI",
            "Crake's World",
            "Cressida",
            "Cretacia",
            "Croatoa",
            "Crux",
            "Cryptus",
            "Cthonia",
            "Cullrak",
            "Curwen",
            "Cybele",
            "Cyclonis",
            "Cyclopea",
            "Cyclopean Prime",
            "Cypra Mundi",
            "Cyprian's Gate",
            "Cyrene",
            "Cyris",
            "Cyrus Vulpa",
            "Cystan",
            "Cytheria",
            "D'yanoi",
            "Dal'yth",
            "Dalthus",
            "Damnia",
            "Damnos",
            "Danik's World",
            "Dantium",
            "Dantris III",
            "Darcia",
            "Darendara",
            "Darillia",
            "Darkenhel",
            "Darkhold",
            "Davin",
            "Delaphina",
            "Deliverance",
            "Dellerax",
            "Delta Arbuthnot",
            "Delta Tao",
            "Denkari Minor",
            "Derdoni",
            "Derwynia",
            "Devlan",
            "Dheneb",
            "Dhol VI",
            "Diesos",
            "Dimmamar",
            "Dolsia",
            "Don-Croix",
            "Dorrholtz",
            "Dorvastor",
            "Doton",
            "Drachu",
            "Draconith",
            "Drade-73",
            "Drakaasi",
            "Draven",
            "Drazak",
            "Dreah",
            "Drex",
            "Drook VI",
            "Drusus",
            "Dulan",
            "Dunen II",
            "Dunroamin VI",
            "Dusk",
            "Duthovan",
            "Dwimlicht",
            "Dykastra",
            "Dynax Primus",
            "Eden Prime",
            "Eidolon",
            "Elara Prime",
            "Eldritch",
            "Elnath",
            "Elros",
            "Elsy'eir",
            "Elusia Prime",
            "Elysia",
            "Elysiar",
            "Emele",
            "Emiline's Hope",
            "Endrite",
            "Endymion Prime",
            "Ephaeda",
            "Ephisia",
            "Ephraeleon",
            "Epsion Octarius",
            "Erenon",
            "Ergotia",
            "Erridas",
            "Erwynn's World",
            "Es'Tau",
            "Esko",
            "Espandor",
            "Estaban III",
            "Estaban VII",
            "Eswulus",
            "Etiamnun III",
            "Eurytion",
            "Evangel",
            "Eydolim",
            "Eyrie",
            "Fal'shia",
            "Fedrid",
            "Felis",
            "Fell Core",
            "Fenksworld",
            "Fenris",
            "Ferroxian",
            "Fervious",
            "Fi'rios",
            "Finreht Three-Seven",
            "Firestorm",
            "Fleur-de-Fides",
            "Florins",
            "Flotte",
            "Fool's Paradise",
            "Fordris",
            "Forge Polix",
            "Forgefane",
            "Formal Prime",
            "Fornax Aleph",
            "Fortis Binary",
            "Fortress",
            "Foth III",
            "Foth VI",
            "Framlingham",
            "Furund",
            "Gacrux",
            "Gaero Alphus",
            "Galan V",
            "Galaspar",
            "Galathas II",
            "Galavan",
            "Gallilenus III",
            "Galmor",
            "Gamara 12",
            "Gammenon IX",
            "Ganf Magna",
            "Garaghak's World",
            "Gargathea III",
            "Garm",
            "Garomar",
            "Gath Rimmon",
            "Gathalamor",
            "Gathis II",
            "Gehenna",
            "Gehenna Prime",
            "Gehöft",
            "Genarius Prime",
            "Geratomro",
            "Gereon",
            "Ghalmek",
            "Gheden",
            "Gheistos",
            "Ghinga",
            "Ghorstangrad",
            "Ghül",
            "Gidrim",
            "Gilreh",
            "Gloriam",
            "Gnosis Prime",
            "Go'shol",
            "Gohliath IV",
            "Golgotha",
            "Golia VII",
            "Gonomondium",
            "Gonoria Prime",
            "Goranado",
            "Gorgonum",
            "Gorkamorka",
            "Gororan III",
            "Goru-Prime",
            "Goth",
            "Govina",
            "Graffias",
            "Graia",
            "Grangold",
            "Granithor",
            "Gravalax",
            "Greater Eydolim",
            "Grendel's World",
            "Grimoyr",
            "Gruss",
            "Gryphonne IV",
            "Gudrun",
            "Guer III",
            "Gunpoint",
            "Guryan",
            "Guytoga",
            "Gythos",
            "Haakonath",
            "Haark",
            "Hadd",
            "Haddrack",
            "Hadleys Hope",
            "Hagia",
            "Hamooth",
            "Harakon",
            "Harkon",
            "Haxan Prime",
            "Hazhim",
            "Heckla",
            "Hegelian IX",
            "Heidrun",
            "Heletine",
            "Helios",
            "Hellgrace",
            "Hermetica",
            "Herod",
            "Herodor",
            "Hesh",
            "Hesiod's Wake",
            "Hesperax",
            "Het",
            "Heterodyne",
            "Hethgar Prime",
            "Hexis Alpha",
            "Hilarion",
            "Hlatan",
            "Ho'sarn",
            "Hoight",
            "Holda",
            "Honourum",
            "Horestis",
            "Hranx",
            "Hredrin",
            "Hubris",
            "Hurspraxia",
            "Husk",
            "Hyades",
            "Hyannoth IV",
            "Hydra Minoris",
            "Hydraphur",
            "Hypasitis",
            "Hypnoth",
            "Hyraq II",
            "Iax",
            "Icefang",
            "Ichar IV",
            "Ichorax",
            "Ichoria",
            "Ichovor",
            "Ichtar IX",
            "Idumea",
            "Iduno",
            "Idyll",
            "Iesta Veracrux",
            "Ignatius Cardinal",
            "Incaladion",
            "Inferria-Prime",
            "Ingiga",
            "Innocence III",
            "Inwit",
            "Iocanthos",
            "Ironghast Foundry",
            "Ironhelm",
            "Isla'su",
            "Isstvan III",
            "Isstvan V",
            "Ithaka",
            "Ixya",
            "Izzakos",
            "Jaggafall",
            "Jago",
            "Jagun",
            "Japheth",
            "Jared's World",
            "Jollana",
            "Jones Crispin World",
            "Jorun's World",
            "Jouran",
            "Jubal",
            "Jumael IV",
            "Jupiter",
            "Jurn",
            "K'otal",
            "K’ail",
            "Ka'mais",
            "Kaenis V",
            "Kai",
            "Kaladrone",
            "Kaledon",
            "Kalf",
            "Kalidar I",
            "Kalidar II",
            "Kalidar III",
            "Kalidar IV",
            "Kaliman IV",
            "Kallista",
            "Kamenka Troika",
            "Kanak",
            "Kanzuz IX",
            "Kapella 47",
            "Kar Duniash",
            "Karkariad",
            "Karnak II",
            "Karnax 17",
            "Karrik",
            "Kastorel-Novem",
            "Kataris",
            "Kathalon",
            "Kathur",
            "Kato",
            "Kaurava I",
            "Kaurava II",
            "Kaurava III",
            "Kaurava IV",
            "KCX-1288",
            "Ke'lshan",
            "Keletros",
            "Kenov III",
            "Kentaur",
            "Keylek",
            "Khai-zhan",
            "Khedd 1173",
            "Khongkotan",
            "Khoraj",
            "Khur",
            "Khymara",
            "Kiavahr",
            "Kimmeria",
            "Klaihn",
            "Klithaine",
            "Klybo",
            "Knarr",
            "Kodiak Prime",
            "Kolagar",
            "Kommitzar",
            "Kovalic II",
            "Kragh",
            "Krandor III",
            "Kreinaath",
            "Krieg",
            "Kronus",
            "Krourk",
            "Ksi'm'yen",
            "Kulth",
            "Lacusta",
            "Laius Rift",
            "Lammas",
            "Landunder",
            "Lassiv",
            "Lathes",
            "Lavantia",
            "Laymon",
            "Lector's Lowel",
            "Lehyde Ten",
            "Lesser Nox",
            "Lethe Eleven",
            "Lethys",
            "Levion Gamma",
            "Libethra",
            "Ligeria",
            "Lilia Mundi",
            "Lima Rogan",
            "Limnus Epsilon",
            "Lissandro",
            "Llagris",
            "Lo",
            "Lodius",
            "Loqiit",
            "Lorin Alpha",
            "Lorn V",
            "Lostok",
            "Lucid Prime",
            "Lucius",
            "Luggnum",
            "Luther Macintyre IX",
            "Luxor",
            "Luxor (Gothic Sector)",
            "Lycosidae",
            "M'khand",
            "M'Laar XIII",
            "Maccabeus Quintus",
            "Macharia",
            "Macharia (Obscurus)[Needs Citation]",
            "Machiun",
            "Macragge",
            "Magdaelene IX",
            "Magnax V",
            "Magnos Omicron",
            "Mahr'douk",
            "Malbolge IV",
            "Malfi",
            "Malice",
            "Malodrax",
            "Malvolion",
            "Mancora",
            "Mandragora",
            "Manzipor",
            "Mara",
            "Marfak",
            "Mariach",
            "Marioch",
            "Mars",
            "Marunda II",
            "Masali",
            "Mataras IV",
            "Maypax",
            "Medrengard",
            "Medusa",
            "Medusa V",
            "Megheim",
            "Megiddio Primus",
            "Mekbuda",
            "Mekslag-llks",
            "Melchior",
            "Menazoid Epsilon",
            "Mendona",
            "Merga",
            "Merida",
            "Meridian",
            "Merov",
            "Merovincha",
            "Messia",
            "Metalica",
            "Methalor",
            "Methusela",
            "Mezoa",
            "MG-Dyel",
            "Minea",
            "Minerva",
            "Miral II",
            "Mithron",
            "Modren Prime",
            "Moebius",
            "Moirae",
            "Monrass",
            "Montsegnur",
            "Mordant Prime",
            "Mordax",
            "Mordian",
            "Mordriana III",
            "Moredakka",
            "Moriorum",
            "Morlond",
            "Morrigar",
            "Morrigor",
            "Mortikah VII",
            "Mortressa",
            "Morwen VI",
            "Mpandex",
            "Mu'gulath Bay",
            "Mundus Planus",
            "Mundus Pyra",
            "Murder",
            "Murzim",
            "Mysibis",
            "N'dras",
            "Na'jadar",
            "Nagathar",
            "Nalibraxis II",
            "Nanthrax III",
            "Naogeddon",
            "Naos",
            "ND0/K4",
            "Nebrus IX",
            "Necris",
            "Necromunda",
            "Nedicta Secundus",
            "Nekkar",
            "Nemesis Tessera",
            "Neptune",
            "Neutra",
            "New Badab",
            "New Bylar",
            "New Muin",
            "Newfound",
            "Newseam",
            "Nihilas",
            "Nimbosa",
            "Nocturne",
            "Nomanus",
            "Nonimax",
            "Nostramo",
            "Nurth",
            "Nymidae",
            "Obsidia",
            "Occludus",
            "Octarius",
            "Ogrys",
            "Oldarian",
            "Olympia",
            "Omeros",
            "Omnicron 71-DX",
            "Ootheca",
            "Ophelia VII",
            "Ophelion",
            "Opus Macharius",
            "Orana",
            "Orar",
            "Orask",
            "Orbel Quill",
            "Ordana",
            "Orestes",
            "Oriflame",
            "Orlen",
            "Orlenza Triartes",
            "Orpheus Prime",
            "Orphidia Delta",
            "Orphidia Prime",
            "Orthoda Rex",
            "Oscillia IX",
            "Outrenacht",
            "Oxatan",
            "Palatine III",
            "Palomar",
            "Pandora Prime",
            "Parabulus",
            "Paraghast",
            "Paragon",
            "Paramar",
            "Paramar V",
            "Paraxus",
            "Parosa",
            "Pavar V",
            "Pavonis",
            "Pax",
            "Pech",
            "Pelius",
            "Pellucida IX",
            "Percipre",
            "Perinetus",
            "Periremunda",
            "Perlia",
            "Persepolis",
            "Pervigilium",
            "Phaenon Prime",
            "Phaethon IV",
            "Phaeton",
            "Phagir",
            "Phaistos Osiris",
            "Phalan 10",
            "Phobian",
            "Phobos",
            "Phyressia",
            "Phyrr",
            "Picus",
            "Piety",
            "Piety of Seth",
            "Pilgrim's Pause",
            "Pintax",
            "Piscina IV",
            "Plague Planet",
            "Planet of the Sorcerers",
            "Plutol",
            "Pluvioris",
            "Porphetus",
            "Port Sanctus",
            "Port Veruca",
            "Posul",
            "Praedis Zeta",
            "Praesidia",
            "Praetoria",
            "Pranagar",
            "Prandium",
            "Preyspire",
            "Prism",
            "Prixetti VII",
            "Prol IX",
            "Prospero",
            "Protasia",
            "Protheus",
            "Purgatory",
            "Pylar",
            "Pyran",
            "Pyrites",
            "Pyrrhia",
            "Quaddis",
            "Quatara-Prime",
            "Quatra",
            "Queh-quih",
            "Quintarn",
            "Quintus",
            "Qulus Trine",
            "Radnar",
            "Raikan",
            "Ral'eth",
            "Rana",
            "Rand XXI",
            "Rann",
            "Raxos",
            "Rayvenscrag IV",
            "Regulus",
            "Reth",
            "Reznor",
            "Rhanda",
            "Rhodus",
            "Rhorsch",
            "Ritzos",
            "Rovanat IV",
            "Rygar",
            "Rylan",
            "Rynn's World",
            "Ryza",
            "Sa'cea",
            "Sabatine",
            "Sable",
            "Sacris",
            "Saganor",
            "Saint Marduk's Bane",
            "Salem",
            "Salem Proctor",
            "Sallan's World",
            "Salomine",
            "Samax IV",
            "Samech",
            "Sameter",
            "Samson IV",
            "San Guisaga",
            "San Leor",
            "Sancour",
            "Sanctum",
            "Sanctus Lys",
            "Sans Gaviria",
            "Saras VII",
            "Sarius V",
            "Sarkon",
            "Sarosel",
            "Sarum",
            "Saturn",
            "Scathe",
            "Scelus",
            "Schrodinger VII",
            "Scintilla",
            "Scound's Fall",
            "Secunda",
            "Seidon",
            "Semus",
            "Sepharis Ultra",
            "Sepheris Secundus",
            "Septimus Moore",
            "Settlement 228",
            "Sha'draig",
            "Shadoworld of Adun",
            "Shardenus",
            "Sharlor",
            "Shemnoch",
            "Shenlong",
            "Sicarus",
            "Siculi",
            "Sigma-Agrius",
            "Silence",
            "Simia Orichalcae",
            "Sinophia",
            "Sisk",
            "Sixty-Three-Nineteen",
            "Skardenfel",
            "Skeros",
            "Skorgulian",
            "Sleef",
            "Smelter's Heap",
            "Solemnace",
            "Solemnus",
            "Solshen XIX",
            "Solstice",
            "Somonor",
            "Sondheim V",
            "Sophano Prime",
            "Soprony",
            "Soryth",
            "Sotha",
            "Sparme",
            "Spectoris",
            "St. Astrid's Fall",
            "St. Guise",
            "St. Salvus Dock",
            "Stalinvast",
            "Sternac",
            "Stonekraal",
            "Strank",
            "Stygia XII",
            "Stygia-Aquilon",
            "Stygian Prime",
            "Stygies VIII",
            "Subiaco Diablo",
            "Sulo",
            "Sulyvan",
            "Suranas",
            "Surealis VI",
            "Surtur",
            "Sycorax",
            "Sylphis II",
            "Symeon",
            "Synford",
            "Syrinx",
            "T'au",
            "T'olku",
            "T'ros",
            "Taeloth",
            "Tahnel",
            "Talasa Prime",
            "Talassar",
            "Talithia",
            "Tallarn",
            "Talon",
            "Talus IV",
            "Tan",
            "Tanakreg",
            "Tancredi",
            "Tanis",
            "Tanis (Hive World)",
            "Tanith",
            "Tanstar 88",
            "Taran III",
            "Tarentus",
            "Targus VIII",
            "Tarrenthorst",
            "Tarsis Ultra",
            "Tartarus",
            "Tash'var",
            "Taslan's Forge",
            "Tassilon",
            "Taygeta",
            "Tekarn",
            "Telemachus",
            "Tellerax Prime",
            "Temaxia",
            "Temperis",
            "Temportus",
            "Tephaine Minor",
            "Terion",
            "Terra",
            "Terrax",
            "Tertius",
            "Teruxyne",
            "Tethris",
            "Thain",
            "Thain II",
            "Thanatos",
            "Thantus X",
            "Thargorum",
            "Theron",
            "Thical",
            "Thoth",
            "Thracian Primaris",
            "Thranx",
            "Threnos",
            "Thridia",
            "Thruscas Sine",
            "Tigrus",
            "Titan (Moon)",
            "Toil",
            "Tolkhan",
            "Toreus",
            "Torhaven",
            "Torian",
            "Torison VII",
            "Torvendis",
            "Traekonnis Major",
            "Trakonn",
            "Tranch",
            "Tranquility II",
            "Tranquility-III",
            "Translock",
            "Trantis",
            "Treconandal",
            "Trepytos",
            "Triandr",
            "Triplex Phall",
            "Trontium VI",
            "Trontiux III",
            "Troudor",
            "Tsade II",
            "Tsan Domus",
            "Turren Primus",
            "Tusk",
            "Tygress I",
            "Tygress II",
            "Tygress III",
            "Tygress IV",
            "Tygress V",
            "Typhon Primaris",
            "Tyrama Secundus",
            "Tyran",
            "UB-26",
            "Uldan",
            "Ultra Maximus",
            "Unloth",
            "Uolesh",
            "Ur-Clemait",
            "Ur-haven",
            "Uralan",
            "Uralek Prime",
            "Urdesh",
            "Urk",
            "Urus",
            "Uttu Prime",
            "V'run",
            "Va'yun",
            "Valhalla",
            "Vallyx V",
            "Valon Urr",
            "Valos",
            "Valos Krin",
            "Vanaheim",
            "Vanqualis",
            "Vardan",
            "Varestus Prime",
            "Varoli Secundus",
            "Varsavia",
            "Vaust",
            "Vaxanide",
            "Vaznagrod",
            "Veneris",
            "Veonid",
            "Verdan II",
            "Verdant",
            "Verdus Prime",
            "Verghast",
            "Verica VII",
            "Veridian",
            "Vernalis",
            "Veskepine",
            "Vespid",
            "Vhospis",
            "Victrix Sonora",
            "Victus",
            "Vigil",
            "Vigilus",
            "Vior'la",
            "Viridia",
            "Visse'el",
            "Volghast",
            "Volonx",
            "Volscar",
            "Voltemand",
            "Vorg Prime",
            "Vorlanthus IV",
            "Vorsk",
            "Voss Prime",
            "Vostroya",
            "Voth",
            "Vraks Prime",
            "Vrantis III",
            "Wezn",
            "Winterhome IX",
            "Woe",
            "World of Immortal Sorrows",
            "Wormgyre",
            "Xana II",
            "Xandros",
            "Xarsis Plethis",
            "Xenax",
            "XIII",
            "Xin-Cyn",
            "Xit",
            "Y'gharnak",
            "Yarant",
            "Ymnar",
            "Yngirheim",
            "Yngroth",
            "Ynnen",
            "Yrnax",
            "Ysai Ydumee",
            "Yspotua",
            "Yu'Kanesh",
            "Yulan",
            "Zaebus Minoris",
            "Zaga IV",
            "Zalamis",
            "Zambeque",
            "Zantium",
            "Zantragora",
            "Zaramund",
            "Zavamunda",
            "Zel Primus",
            "Zel Secundus",
            "Zel Tertius",
            "Zephyr",
            "Zhao-Arkkad",
            "Zhoros",
            "Zibal",
            "Zoran",
            "Zosma"
        };
    }
}